// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=../mock/mock_user.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	model "app/model"
	proxy "app/proxy"
	request "app/request"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserDAOProxy is a mock of UserDAOProxy interface.
type MockUserDAOProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserDAOProxyMockRecorder
	isgomock struct{}
}

// MockUserDAOProxyMockRecorder is the mock recorder for MockUserDAOProxy.
type MockUserDAOProxyMockRecorder struct {
	mock *MockUserDAOProxy
}

// NewMockUserDAOProxy creates a new mock instance.
func NewMockUserDAOProxy(ctrl *gomock.Controller) *MockUserDAOProxy {
	mock := &MockUserDAOProxy{ctrl: ctrl}
	mock.recorder = &MockUserDAOProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDAOProxy) EXPECT() *MockUserDAOProxyMockRecorder {
	return m.recorder
}

// AddFollower mocks base method.
func (m *MockUserDAOProxy) AddFollower(ctx context.Context, followerUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFollower", ctx, followerUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFollower indicates an expected call of AddFollower.
func (mr *MockUserDAOProxyMockRecorder) AddFollower(ctx, followerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFollower", reflect.TypeOf((*MockUserDAOProxy)(nil).AddFollower), ctx, followerUUID)
}

// Create mocks base method.
func (m *MockUserDAOProxy) Create(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserDAOProxyMockRecorder) Create(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDAOProxy)(nil).Create), ctx)
}

// Delete mocks base method.
func (m *MockUserDAOProxy) Delete(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserDAOProxyMockRecorder) Delete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDAOProxy)(nil).Delete), ctx)
}

// Email mocks base method.
func (m *MockUserDAOProxy) Email(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockUserDAOProxyMockRecorder) Email(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockUserDAOProxy)(nil).Email), arg0)
}

// Gender mocks base method.
func (m *MockUserDAOProxy) Gender(arg0 model.UserGender) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gender", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Gender indicates an expected call of Gender.
func (mr *MockUserDAOProxyMockRecorder) Gender(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gender", reflect.TypeOf((*MockUserDAOProxy)(nil).Gender), arg0)
}

// Get mocks base method.
func (m *MockUserDAOProxy) Get(ctx context.Context) (*model.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*model.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserDAOProxyMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserDAOProxy)(nil).Get), ctx)
}

// GetViaUsername mocks base method.
func (m *MockUserDAOProxy) GetViaUsername(ctx context.Context, username string) (*model.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViaUsername", ctx, username)
	ret0, _ := ret[0].(*model.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViaUsername indicates an expected call of GetViaUsername.
func (mr *MockUserDAOProxyMockRecorder) GetViaUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViaUsername", reflect.TypeOf((*MockUserDAOProxy)(nil).GetViaUsername), ctx, username)
}

// Icon mocks base method.
func (m *MockUserDAOProxy) Icon(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Icon", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Icon indicates an expected call of Icon.
func (mr *MockUserDAOProxyMockRecorder) Icon(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Icon", reflect.TypeOf((*MockUserDAOProxy)(nil).Icon), arg0)
}

// Introduction mocks base method.
func (m *MockUserDAOProxy) Introduction(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introduction", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Introduction indicates an expected call of Introduction.
func (mr *MockUserDAOProxyMockRecorder) Introduction(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introduction", reflect.TypeOf((*MockUserDAOProxy)(nil).Introduction), arg0)
}

// Password mocks base method.
func (m *MockUserDAOProxy) Password(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Password", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Password indicates an expected call of Password.
func (mr *MockUserDAOProxyMockRecorder) Password(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Password", reflect.TypeOf((*MockUserDAOProxy)(nil).Password), arg0)
}

// Region mocks base method.
func (m *MockUserDAOProxy) Region(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Region", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Region indicates an expected call of Region.
func (mr *MockUserDAOProxyMockRecorder) Region(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Region", reflect.TypeOf((*MockUserDAOProxy)(nil).Region), arg0)
}

// RemoveFollower mocks base method.
func (m *MockUserDAOProxy) RemoveFollower(ctx context.Context, followerUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFollower", ctx, followerUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFollower indicates an expected call of RemoveFollower.
func (mr *MockUserDAOProxyMockRecorder) RemoveFollower(ctx, followerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFollower", reflect.TypeOf((*MockUserDAOProxy)(nil).RemoveFollower), ctx, followerUUID)
}

// SearchViaUsername mocks base method.
func (m *MockUserDAOProxy) SearchViaUsername(ctx context.Context, username string) ([]*model.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchViaUsername", ctx, username)
	ret0, _ := ret[0].([]*model.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchViaUsername indicates an expected call of SearchViaUsername.
func (mr *MockUserDAOProxyMockRecorder) SearchViaUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchViaUsername", reflect.TypeOf((*MockUserDAOProxy)(nil).SearchViaUsername), ctx, username)
}

// UUID mocks base method.
func (m *MockUserDAOProxy) UUID(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UUID", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// UUID indicates an expected call of UUID.
func (mr *MockUserDAOProxyMockRecorder) UUID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UUID", reflect.TypeOf((*MockUserDAOProxy)(nil).UUID), arg0)
}

// Update mocks base method.
func (m *MockUserDAOProxy) Update(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserDAOProxyMockRecorder) Update(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDAOProxy)(nil).Update), ctx)
}

// Username mocks base method.
func (m *MockUserDAOProxy) Username(arg0 string) proxy.UserDAOProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Username", arg0)
	ret0, _ := ret[0].(proxy.UserDAOProxy)
	return ret0
}

// Username indicates an expected call of Username.
func (mr *MockUserDAOProxyMockRecorder) Username(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Username", reflect.TypeOf((*MockUserDAOProxy)(nil).Username), arg0)
}

// MockUserServiceProxy is a mock of UserServiceProxy interface.
type MockUserServiceProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceProxyMockRecorder
	isgomock struct{}
}

// MockUserServiceProxyMockRecorder is the mock recorder for MockUserServiceProxy.
type MockUserServiceProxyMockRecorder struct {
	mock *MockUserServiceProxy
}

// NewMockUserServiceProxy creates a new mock instance.
func NewMockUserServiceProxy(ctrl *gomock.Controller) *MockUserServiceProxy {
	mock := &MockUserServiceProxy{ctrl: ctrl}
	mock.recorder = &MockUserServiceProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceProxy) EXPECT() *MockUserServiceProxyMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServiceProxy) CreateUser(arg0 context.Context, arg1 *request.UserCreateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceProxyMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceProxy)(nil).CreateUser), arg0, arg1)
}

// MockUserUtilsProxy is a mock of UserUtilsProxy interface.
type MockUserUtilsProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserUtilsProxyMockRecorder
	isgomock struct{}
}

// MockUserUtilsProxyMockRecorder is the mock recorder for MockUserUtilsProxy.
type MockUserUtilsProxyMockRecorder struct {
	mock *MockUserUtilsProxy
}

// NewMockUserUtilsProxy creates a new mock instance.
func NewMockUserUtilsProxy(ctrl *gomock.Controller) *MockUserUtilsProxy {
	mock := &MockUserUtilsProxy{ctrl: ctrl}
	mock.recorder = &MockUserUtilsProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUtilsProxy) EXPECT() *MockUserUtilsProxyMockRecorder {
	return m.recorder
}

// EncryptPassword mocks base method.
func (m *MockUserUtilsProxy) EncryptPassword(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptPassword", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptPassword indicates an expected call of EncryptPassword.
func (mr *MockUserUtilsProxyMockRecorder) EncryptPassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptPassword", reflect.TypeOf((*MockUserUtilsProxy)(nil).EncryptPassword), arg0)
}

// GenerateUUID mocks base method.
func (m *MockUserUtilsProxy) GenerateUUID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUUID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateUUID indicates an expected call of GenerateUUID.
func (mr *MockUserUtilsProxyMockRecorder) GenerateUUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUUID", reflect.TypeOf((*MockUserUtilsProxy)(nil).GenerateUUID))
}

// ValidatePassword mocks base method.
func (m *MockUserUtilsProxy) ValidatePassword(hPassword, password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", hPassword, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockUserUtilsProxyMockRecorder) ValidatePassword(hPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockUserUtilsProxy)(nil).ValidatePassword), hPassword, password)
}
